.system/arachni-ui-web/config/routes.rb
=begin
    Copyright 2013-2022 Ecsypno <http://www.ecsypno.com>

    This file is part of the Arachni WebUI project and is subject to
    redistribution and commercial restrictions. Please see the Arachni WebUI
    web site for more information on licensing and terms of use.
=end

ArachniWebui::Application.routes.draw do
    resources :settings

    resources :notifications, only: [:mark_all_read, :destroy] do
        patch :mark_read, on: :collection
    end

    resources :dispatchers do
        patch :make_default, on: :member
        patch :share,        on: :member
    end

    scope 'scans' do
        resources :scan_groups, path: 'groups',
                  only: [ :new, :edit, :create, :update, :destroy ]
    end

    resources :scans do
        resources :comments
        resources :issues, only: [ :index, :show, :update ] do
            resources :comments
        end

        post :repeat,   on: :member

        patch :update_memberships,    on: :member
        patch :suspend,  on: :member
        patch :restore,  on: :member
        patch :share,    on: :member
        patch :pause,    on: :member
        patch :resume,   on: :member
        patch :abort,    on: :member

        post  :import,   on: :collection

        patch :suspend,  on: :collection, to: :suspend_all
        patch :pause,    on: :collection, to: :pause_all
        patch :resume,   on: :collection, to: :resume_all
        patch :abort,    on: :collection, to: :abort_all

        get :new_revision, on: :member
        get :report,   on: :member
        get :comments, on: :member
        get :errors,   on: :member
        get :count,    on: :collection
        get :schedule, on: :collection
    end

    resources :profiles do
        post  :import,       on: :collection
        patch :make_default, on: :member
        patch :share,        on: :member
        get   :copy,         on: :member
    end

    get '/navigation', :to => 'home#navigation'
    get '/welcome',    :to => 'home#welcome'

    root to: 'home#index'

    devise_for :users, :skip => [:registrations], path_prefix: 'd'
    as :user do
        get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
        patch 'users' => 'devise/registrations#update', as: 'user_registration'
    end
    resources :users
end

.system/arachni-ui-web/app/views/layouts/_breadcrumbs.html.erb
<% if breadcrumbs.any? %>
    <nav class="breadcrumbs">
        <div class="container">
            <ul class="bread">
                <li>
                    <%= link_to root_path do %>
                        <i class="icon-home icon-white"></i>
                    <% end %>
                </li>
                <% breadcrumbs.each do |b| %>
                <li>
                    <%= link_to b[:title], b[:url] %>
                </li>
                <% end %>
                <li>
                    <%= link_to yield( :title ), request.path, class: 'active' %>
                </li>
            </ul>
        </div>
    </nav>
<% end %>

.system/arachni-ui-web/app/views/layouts/_messages.html.erb
<% if fade_out_messages? %>
    <div id="flash">
        <% flash.each do |name, msg| %>
            <div class="alert alert-<%= name.to_sym == :notice ? 'success' : 'error' %>">
                <a class="close" data-dismiss="alert">&#10006;</a>
                <%= content_tag :div, msg, id: "#{name}" if msg.is_a?( String ) %>
            </div>
        <% end %>
    </div>
<% else %>
    <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name.to_sym == :notice ? 'success' : 'error' %>">
            <a class="close" data-dismiss="alert">&#10006;</a>
            <%= content_tag :div, msg, id: "#{name}" if msg.is_a?( String ) %>
        </div>
    <% end %>
<% end %>

.system/arachni-ui-web/app/views/layouts/_navigation.html.erb
<%= link_to "WAPT", root_path, class: 'brand' %>

<% if user_signed_in? %>

    <div id="phone-menu" class="nav visible-phone">
        <a class="btn btn-navbar dropdown-toggle" data-toggle="dropdown" href="#">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <ul class="dropdown-menu">
            <li>
                <%= link_to scans_path, class: 'dropdown-toggle disabled', data: { toggle: 'dropdown' } do %>
                    Scans

                    <% if (scan_acount = current_user.scans.active.count) > 0 %>
                        <span id="active-scan-counter" class="label"><%= scan_acount %></span>
                    <% end %>
                <% end %>
            </li>
            <li>
                <%= link_to profiles_path, class: 'dropdown-toggle disabled', data: { toggle: 'dropdown' } do %>
                    Profiles
                <% end %>
            </li>
            <li class="dropdown">
                <%= link_to dispatchers_path, class: 'dropdown-toggle disabled', data: { toggle: 'dropdown' } do %>
                    Dispatchers
                <% end %>
            </li>
            <% if can? :read, User %>
                <li>
                    <%= link_to users_path, class: 'dropdown-toggle disabled', data: { toggle: 'dropdown' } do %>
                        Users
                    <% end %>
                </li>
            <% end %>
            <% if can? :read, Setting %>
                <li><%= link_to 'Settings', settings_path %></li>
            <% end %>
        </ul>
    </div>

    <ul class="nav hidden-phone">
        <li class="dropdown">
            <%= link_to scans_path, class: 'dropdown-toggle disabled', data: { toggle: 'dropdown' } do %>
                Scans

                <% if (scan_acount = current_user.scans.active.count) > 0 %>
                    <span id="active-scan-counter" class="label"><%= scan_acount %></span>
                <% end %>

                <b class="caret"></b>
            <% end %>

            <ul id="scan-dropdown" class="dropdown-menu">
                <li>
                    <%= link_to new_scan_path do %>
                        <i class="icon-plus"></i>
                        New
                    <% end %>
                </li>

                <li>
                    <%= link_to schedule_scans_path do %>
                        <i class="icon-calendar"></i>
                        Schedule
                    <% end %>
                </li>

                <% if (recent_scans = current_user.scans.active.recent).any? %>
                    <li class="divider"></li>
                    <li class="nav-header">Recently started</li>
                    <% recent_scans.each do |scan| %>
                        <li>
                            <%= link_to scan,
                                        scan_path( scan ),
                                        class: ("alert-warning" if scan.paused?),
                                        title: ("Paused" if scan.paused?)
                            %>
                        </li>
                    <% end %>
                <% end %>

                <% if (recent_scans = current_user.scans.finished.recent).any? %>
                    <li class="divider"></li>
                    <li class="nav-header">Recently finished</li>
                    <% recent_scans.each do |scan| %>
                        <%
                           opts = if scan.error?
                               { class: "alert-error", title: "Error" }
                           elsif scan.aborted?
                               { class: "alert-warning", title: "Aborted" }
                           end
                        %>
                        <li>
                            <%= link_to scan, scan_path( scan ), opts %>
                        </li>
                    <% end %>
                <% end %>
            </ul>
        </li>

        <li class="dropdown">
            <%= link_to profiles_path, class: 'dropdown-toggle disabled', data: { toggle: 'dropdown' } do %>
                Profiles
                <b class="caret"></b>
            <% end %>

            <ul id="profile-dropdown" class="dropdown-menu">
                <% if can? :create, Profile %>
                <li>
                    <%= link_to new_profile_path do %>
                        <i class="icon-plus"></i>
                        New
                    <% end %>
                </li>
                <% end %>

                <% if (recent_profiles = current_user.available_profiles.light.recent).any? %>
                    <li class="divider"></li>
                    <li class="nav-header">Recently added</li>
                    <% recent_profiles.each do |profile| %>
                        <li><%= link_to profile, profile_path( profile ) %></li>
                    <% end %>
                <% end %>

            </ul>
        </li>

        <% has_dropdown = (recent_dispatchers = current_user.available_dispatchers.recent).any? || can?( :create, Dispatcher ) %>

        <li class="dropdown">
            <%= link_to dispatchers_path, class: 'dropdown-toggle disabled', data: { toggle: 'dropdown' } do %>
                Dispatchers
                <% if has_dropdown %>
                <b class="caret"></b>
                <% end %>
            <% end %>

            <% if has_dropdown %>
            <ul id="dispatcher-dropdown" class="dropdown-menu">

                <% if can? :create, Dispatcher %>
                <li>
                    <%= link_to new_dispatcher_path do %>
                        <i class="icon-plus"></i>
                        New
                    <% end %>
                </li>
                <% end %>

                <% if recent_dispatchers.any? %>
                    <li class="divider"></li>
                    <li class="nav-header">Recently added</li>
                    <% recent_dispatchers.each do |dispatcher| %>
                        <li><%= link_to dispatcher, dispatcher_path( dispatcher ) %></li>
                    <% end %>
                <% end %>

            </ul>
            <% end %>
        </li>

        <% if can? :read, User %>
        <li class="dropdown">
            <%= link_to users_path, class: 'dropdown-toggle disabled', data: { toggle: 'dropdown' } do %>
                Users
                <b class="caret"></b>
            <% end %>

            <ul id="user-dropdown" class="dropdown-menu">
                <% if can? :create, User %>
                    <li>
                        <%= link_to new_user_path do %>
                            <i class="icon-plus"></i>
                            New
                        <% end %>
                    </li>
                <% end %>

                <% if (recent_users = User.recent).any? %>
                    <li class="divider"></li>
                    <li class="nav-header">Recently added</li>
                    <% recent_users.each do |user| %>
                        <li><%= link_to user, user_path( user ) %></li>
                    <% end %>
                <% end %>

            </ul>
        </li>
        <% end %>

    </ul>
<% end %>

<ul class="nav pull-right">
    <% if user_signed_in? %>

        <% if (notifications = current_user.notifications.unread).any? %>
        <li class="dropdown" id="notifications-list">
            <%= link_to root_path, class: 'dropdown-toggle disabled', data: { toggle: 'dropdown' } do %>
                <i class="icon-exclamation-sign"></i>

                <span class="label label-inverse"><%= notifications.count %></span>
                <b class="caret hidden-phone"></b>
            <% end %>

            <ul id="notification-dropdown" class="dropdown-menu hidden-phone">
                <li>
                    <%= link_to mark_read_notifications_path, method: :patch, remote: true do %>
                        <i class="icon-ok"></i>
                        Mark all read
                    <% end %>
                </li>

                <li class="divider"></li>
                <% notifications.each do |notification| %>
                    <li>
                        <% if notification.model %>
                            <%= link_to notification.to_s, polymorphic_path( notification.model.family ) %>
                        <% else %>
                            <%= link_to notification.to_s, '#' %>
                        <% end %>
                    </li>
                <% end %>
            </ul>
        </li>
        <% end %>

    <li>
        <div class="btn-group">
            <a class="btn btn-small btn-primary" href="#">
                <i class="icon-user icon-white"></i>
                <%= current_user.name %>
            </a>

            <a class="btn btn-small btn-primary dropdown-toggle"
               data-toggle="dropdown" href="#">
              <span class="caret"></span>
            </a>
            <ul id="current-user-dropdown" class="dropdown-menu">
                <% if can? :read, Setting %>
                    <li>
                        <%= link_to settings_path do %>
                            <i class="icon-cog"></i> Settings
                        <% end %>
                    </li>
                    <li class="divider"></li>
                <% end %>

                <li>
                  <%= link_to edit_user_registration_path do %>
                      <i class="icon-pencil"></i> Edit account
                  <% end %>
                </li>
                <li>
                <%= link_to destroy_user_session_path, method: 'delete' do %>
                    <i class="icon-off"></i> Sign out
                <% end %>
              </li>
            </ul>
        </div>
    </li>
    <% else %>
    <li>
        <%= link_to 'Sign in', new_user_session_path %>
    </li>
    <% end %>

</ul>

.system/arachni-ui-web/app/views/layouts/_subnav.html.erb
<ul id="sidenav" class="nav nav-pills nav-stacked sidenav">
    <li>
        <a href="#top" class="scroll">
            <%= opts[:top] || 'Top' %>
            <i class="icon-chevron-up"></i>
        </a>
    </li>
    <% sections.each do |id, title| %>
        <li>
            <a href="#<%= id.to_s %>" class="scroll">
                <%= title.to_s.html_safe %>
                <i class="icon-chevron-right"></i>
            </a>
        </li>
    <% end %>
</ul>

.system/arachni-ui-web/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            <%= "#{yield( :title )} - " if content_for?( :title ) %>
            <%= "#{title_breadcrumbs} - " if !title_breadcrumbs.empty? %>
            WAPT
        </title>
        <meta name="description" content="">
        <meta name="author" content="">

        <link rel="shortcut icon" href="/assets/favicon.png" />

        <%= stylesheet_link_tag    "application", media: "all" %>
        <%= javascript_include_tag "application" %>
        <%= csrf_meta_tags %>
        <%= yield( :head ) %>
    </head>
    <body id="top" data-target=".spy" data-spy="scroll">
        <div id="loading" class="hide modal progress progress-striped active">
            <div class="bar" style="width: 100%;"></div>
        </div>

        <header class="navbar navbar-inverse navbar-fixed-top">
            <nav class="navbar-inner">
                <div id="navigation-top" class="container"
                     <% if current_user %>
                     data-refresh-url="<%= navigation_path %>"
                     <%end%>
                     >

                    <%= render 'layouts/navigation' %>
                </div>
            </nav>

            <%= render_breadcrumbs %>
        </header>

        <div id="main" role="main">
            <div class="container-fluid">
                <div id="content" class="content">
                    <div class="row-fluid">

                        <div id="scnr-alert" class="alert alert-info">
                            Welcome <a href="#">WAPT</a>
                            <a href="#">WAPT</a>!
                        </div>

                        <% if show_affixed_sidebar? || show_sidebar? %>
                            <div id="left-sidebar" class="span2 sidebar hidden-phone">

                                <% if show_affixed_sidebar? %>
                                    <div id="sidebar-affix" class="hidden-phone affix">

                                        <div class="row-fluid">
                                            <div>
                                                <%= affixed_sidebar.html_safe %>
                                            </div>
                                        </div>

                                        <% if has_subnav? %>
                                            <div class="spy">
                                                <%= render_subnav %>
                                            </div>
                                        <% end %>
                                    </div>
                                <% end %>

                                <% if show_sidebar? %>
                                    <div class="row-fluid hidden-phone">
                                        <div>
                                            <%= sidebar.html_safe %>
                                        </div>
                                    </div>
                                <% end %>
                            </div>
                        <% end %>

                        <div id="main-content" class="span8">
                            <%= render 'layouts/messages' %>
                            <%= yield.force_encoding( 'utf-8' ) %>
                        </div>
                    </div>
                </div>
            </div> <!--! end of .container -->
        </div> <!--! end of #main -->

        
    </body>
</html>