.system/arachni-ui-web/config/routes.rb
=begin
    Copyright 2013-2022 Ecsypno <http://www.ecsypno.com>

    This file is part of the Arachni WebUI project and is subject to
    redistribution and commercial restrictions. Please see the Arachni WebUI
    web site for more information on licensing and terms of use.
=end

ArachniWebui::Application.routes.draw do
    resources :settings

    resources :notifications, only: [:mark_all_read, :destroy] do
        patch :mark_read, on: :collection
    end

    resources :dispatchers do
        patch :make_default, on: :member
        patch :share,        on: :member
    end

    scope 'scans' do
        resources :scan_groups, path: 'groups',
                  only: [ :new, :edit, :create, :update, :destroy ]
    end

    resources :scans do
        resources :comments
        resources :issues, only: [ :index, :show, :update ] do
            resources :comments
        end

        post :repeat,   on: :member

        patch :update_memberships,    on: :member
        patch :suspend,  on: :member
        patch :restore,  on: :member
        patch :share,    on: :member
        patch :pause,    on: :member
        patch :resume,   on: :member
        patch :abort,    on: :member

        post  :import,   on: :collection

        patch :suspend,  on: :collection, to: :suspend_all
        patch :pause,    on: :collection, to: :pause_all
        patch :resume,   on: :collection, to: :resume_all
        patch :abort,    on: :collection, to: :abort_all

        get :new_revision, on: :member
        get :report,   on: :member
        get :comments, on: :member
        get :errors,   on: :member
        get :count,    on: :collection
        get :schedule, on: :collection
    end

    resources :profiles do
        post  :import,       on: :collection
        patch :make_default, on: :member
        patch :share,        on: :member
        get   :copy,         on: :member
    end

    get '/navigation', :to => 'home#navigation'
    get '/welcome',    :to => 'home#welcome'

    root to: 'home#index'

    devise_for :users, :skip => [:registrations], path_prefix: 'd'
    as :user do
        get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
        patch 'users' => 'devise/registrations#update', as: 'user_registration'
    end
    resources :users
end

.system/arachni-ui-web/app/controllers/profiles_controller.rb
=begin
    Copyright 2013-2022 Ecsypno <http://www.ecsypno.com>

    This file is part of the Arachni WebUI project and is subject to
    redistribution and commercial restrictions. Please see the Arachni WebUI
    web site for more information on licensing and terms of use.
=end

class ProfilesController < ApplicationController
    include ProfilesHelper
    include NotificationsHelper

    before_action :authenticate_user!
    before_action :prepare_plugin_params
    before_action :new_profile, only: [ :create ]

    load_and_authorize_resource

    # GET /profiles
    # GET /profiles.json
    def index
        params.permit!
        prepare_table_data

        respond_to do |format|
            format.html # index.html.erb
            format.js { render '_table.js' }
            format.json { render json: @profiles }
        end
    end

    # GET /profiles/1
    # GET /profiles/1.json
    # GET /profiles/1.yaml
    def show
        @profile = Profile.find( params.require( :id ) )

        set_download_header = proc do |extension|
            name = @profile.name
            [ "\n", "\r", '"' ].each { |k| name.gsub!( k, '' ) }

            headers['Content-Disposition'] =
                "attachment; filename=\"Arachni WebUI Profile - #{name}.#{extension}\""
        end

        respond_to do |format|
            format.html # show.html.erb
            format.js { render @profile }
            format.json do
                set_download_header.call 'json'
                render text: @profile.export( JSON )
            end
            format.yaml do
                set_download_header.call 'yaml'
                render text: @profile.export( YAML )
            end
            format.afp do
                set_download_header.call 'afp'
                render text: @profile.to_rpc_options.to_yaml
            end
        end
    end

    # GET /profiles/new
    # GET /profiles/new.json
    def new
        @profile = Profile.new

        respond_to do |format|
            format.html # new.html.erb
            format.json { render json: @profile }
        end
    end

    # GET /profiles/1/copy
    def copy
        @profile = Profile.find( params.require( :id ) ).dup
        @profile.owner_id = nil
        @profile.global   = false

        respond_to do |format|
            format.html { render 'new' }
        end
    end

    # GET /profiles/1/edit
    def edit
        @profile = Profile.find( params.require( :id ) )
    end

    # PUT /profiles/1/make_default
    def make_default
        profile = Profile.find( params.require( :id ) )

        fail 'Cannot make a non-global profile the default one.' if !profile.global?

        profile.make_default
        params.delete( :id )

        notify profile

        prepare_table_data

        render partial: 'table', formats: :js
    end

    # POST /profiles
    # POST /profiles.json
    def create
        @profile.owner = current_user

        respond_to do |format|
            if @profile.save
                notify @profile

                format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
                format.json { render json: @profile, status: :created, location: @profile }
            else
                format.html { render action: 'new' }
                format.json { render json: @profile.errors, status: :unprocessable_entity }
            end
        end
    end

    # POST /profiles/import
    def import
        if !params[:profile] || !params[:profile][:file].is_a?( ActionDispatch::Http::UploadedFile )
            redirect_to profiles_url, alert: 'No file selected for import.'
            return
        end

        @profile = Profile.import( params[:profile][:file] )

        if !@profile
            redirect_to profiles_url,
                        alert: 'Could not understand the Profile format, please' <<
                            ' ensure that you are using a v0.5 profile.'
            return
        end

        respond_to do |format|
            format.html { render 'edit' }
        end
    end

    # PUT /profiles/1
    # PUT /profiles/1.json
    def update
        @profile = Profile.find( params.require( :id ) )

        respond_to do |format|
            if @profile.update_attributes( strong_params )
                notify @profile

                format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
                format.json { head :no_content }
            else
                format.html { render action: "edit" }
                format.json { render json: @profile.errors, status: :unprocessable_entity }
            end
        end
    end

    def share
        @profile = Profile.find( params.require( :id ) )

        respond_to do |format|
            if @profile.update_attributes( params.require( :profile ).permit( user_ids: [] ) )
                notify @profile

                format.html { redirect_back fallback_location: profiles_path, notice: 'Profile was successfully shared.' }
                format.json { head :no_content }
            else
                format.html { render action: "edit" }
                format.json { render json: @profile.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /profiles/1
    # DELETE /profiles/1.json
    def destroy
        @profile = Profile.find( params.require( :id ) )
        fail 'Cannot delete default Profile.' if @profile.default?
        fail 'Cannot delete Profiles assigned to scheduled Scans.' if @profile.has_scheduled_scans?

        notify @profile
        @profile.destroy

        respond_to do |format|
            format.html { redirect_to profiles_url }
            format.json { head :no_content }
        end
    end

    private

    def new_profile
        @profile = Profile.new( strong_params )
    end

    def strong_params
        plugins_with_options = []
        plugins_with_info = ::FrameworkHelper.plugins
        plugins_with_info.each do |name, info|
            plugins_with_options << (info[:options] ?
                { name => info[:options].map( &:name ) } : name)
        end

        allowed = [
            :name, :audit_cookies, :audit_nested_cookies, :audit_cookies_extensively, :audit_forms,
            :audit_headers, :audit_links, :audit_jsons, :audit_xmls,
            :audit_ui_forms,:audit_ui_inputs, :authorized_by, :scope_auto_redundant_paths,
            :audit_exclude_vector_patterns, :audit_include_vector_patterns,
            :http_cookies, :http_request_headers, :scope_directory_depth_limit,
            :scope_exclude_path_patterns, :scope_exclude_path_patterns_binaries,
            :scope_exclude_path_patterns_cookies, :scope_extend_paths,
            :scope_include_subdomains, :audit_with_both_http_methods,
            :http_request_concurrency, :scope_include_path_patterns,
            :scope_page_limit, :session_check_pattern, :session_check_url,
            :spawns, :min_pages_per_instance, { checks: [] }, { selected_plugins: []},
            { plugins: plugins_with_options }, :http_proxy_host,
            :http_proxy_password, :http_proxy_port, :http_proxy_type,
            :http_proxy_username, :http_request_redirect_limit,
            :scope_redundant_path_patterns, :scope_restrict_paths,
            :http_user_agent, :http_request_timeout, :description,
            :scope_https_only, :scope_exclude_content_patterns, { user_ids: [] },
            :no_fingerprinting, { platforms: [] }, :http_authentication_username,
            :http_authentication_password, :input_values, :browser_cluster_pool_size,
            :browser_cluster_job_timeout, :browser_cluster_worker_time_to_live,
            :browser_cluster_ignore_images, :browser_cluster_screen_width,
            :browser_cluster_screen_height, :scope_dom_depth_limit,
            :audit_link_templates, :http_request_queue_size, :http_response_max_size,
            :scope_url_rewrites, :scope_exclude_binaries, :scope_exclude_file_extensions,
            :http_authentication_type
        ]

        allowed << :global if current_user.admin?

        # Make sure no ActionController::Parameters sneak in.
        params_to_hash params.require( :profile ).permit( *allowed )
    end

    def prepare_plugin_params
        return if !params[:profile]

        if params[:profile][:selected_plugins]
            selected_plugins = {}
            (params[:profile][:selected_plugins] || []).each do |plugin|
                selected_plugins[plugin] = params[:profile][:plugins][plugin]
            end

            params[:profile][:plugins] = selected_plugins
            params[:profile].delete( :selected_plugins )
        else
            params[:profile][:plugins] = {}
        end
    end

    def prepare_table_data
        @profiles = profile_filter( params[:tab] ).page( params[:page] ).
            per( HardSettings.profile_pagination_entries ).
            order( 'id DESC' )

        @counts = {}
        %w(yours shared global).each do |type|
            @counts[type] = profile_filter( type ).count
        end

        @counts['others'] = profile_filter( 'others' ).count if current_user.admin?
    end

end

.system/arachni-ui-web/app/helpers/profiles_helper.rb
=begin
    Copyright 2013-2022 Ecsypno <http://www.ecsypno.com>

    This file is part of the Arachni WebUI project and is subject to
    redistribution and commercial restrictions. Please see the Arachni WebUI
    web site for more information on licensing and terms of use.
=end

module ProfilesHelper
    include ApplicationHelper

    def valid_platforms( type = nil )
        (type.nil? ? platform_manager.valid : platform_manager.send( type ).valid).map( &:to_s )
    end

    def platform_type_fullname( type )
        Arachni::Platform::Manager::TYPES[type]
    end

    def platform_fullname( platform )
        platform_manager.fullname platform
    end

    def platform_manager
        @platform_manager ||= Arachni::Platform::Manager.new
    end

    def modules
        allowed = Settings.profile_allowed_modules.reject { |m| m.to_s.empty?}
        super.select { |name, _| allowed.include? name }
    end

    def plugins
        allowed = Settings.profile_allowed_plugins.reject { |m| m.to_s.empty?}
        super.select { |name, _| allowed.include? name }
    end

    def messages_for( attribute )
        render partial: 'attribute_messages', locals: { attribute: attribute }
    end

    def render_options( plugin_name, plugin_info, configuration = {}, disabled = false )
        tpl = "#{Rails.root}/app/views/profiles/plugin_options/#{plugin_name}/#{params[:action]}.html.erb"
        opts = {
            plugin_name:   plugin_name,
            info:          plugin_info,
            configuration: configuration,
            disabled:      disabled
        }

        if File.exist? tpl
            render file: tpl, locals: opts
        else
            render partial: 'profiles/plugin_options/generic', locals: opts
        end
    end

    def profile_filter( filter )
        filter ||= 'yours'

        case filter
            when 'yours'
                current_user.profiles.where( owner_id: current_user.id )
            when 'shared'
                current_user.profiles.where( "owner_id != ?", current_user.id )
            when 'global'
                Profile.global

            when 'others'
                raise 'Unauthorised!' if !current_user.admin?

                ids = current_user.profiles.select( :id ).
                    where( "owner_id != ?", current_user.id ) +
                    current_user.profiles.select( :id ).
                        where( "owner_id = ?", current_user.id )

                Profile.where( id: Profile.select( :id ) - ids )
        end
    end

    def prepare_description( str )
        placeholder =  '--' + rand( 1000 ).to_s + '--'
        cstr = str.gsub( /^\s*$/xm, placeholder )
        cstr.gsub!( /^\s*/xm, '' )
        cstr.gsub!( placeholder, "\n" )
        cstr.chomp
    end

end

.system/arachni-ui-web/app/views/profiles/_actions.html.erb
<% if can? :edit, profile %>
    <%= link_to edit_profile_path( profile ), title: 'Edit',
                class: 'btn btn-small btn-warning' do %>
        <i class="icon-pencil"></i>
    <% end %>
<% end %>

<% if can? :copy, profile %>
    <%= link_to copy_profile_path( profile ),
                title: "Create a new profile based on '#{profile.name}'",
                class: 'btn btn-small btn-primary' do %>
        <i class="icon-copy"></i>
    <% end %>
<% end %>

<% if can?( :delete, profile ) && !profile.default? && !profile.has_scheduled_scans? %>
    <% msg = 'Are you sure?'
       msg += ' This profile has associated scans.' if profile.scans.any? %>

    <%= link_to profile, title: 'Delete', method: :delete,
                class: 'btn btn-small btn-danger',
                data: { confirm: msg } do %>
        <i class="icon-trash"></i>
    <% end %>
<% end %>

<% if can? :read, profile %>
    <div class="btn-group">
        <a class="btn btn-small btn-inverse" data-toggle="dropdown" href="#">
            <i class="icon-download-alt"></i>
            <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li>
                <%= link_to profile_path( profile, format: :yaml ) do %>
                    YAML
                <% end %>
            </li>
            <li>
                <%= link_to profile_path( profile, format: :json ) do %>
                    JSON
                <% end %>
            </li>
          <li>
            <%= link_to profile_path( profile, format: :afp ) do %>
                AFP (Suitable for the CLI interface.)
            <% end %>
          </li>
        </ul>
    </div>
<% end %>

<% if can? :share, profile %>
    <%= render partial: 'shared/share_form', locals: { model: profile, nolabel: true } %>
<% end %>

.system/arachni-ui-web/app/views/profiles/_attribute_messages.html.erb
<% if description = Profile.description_for( attribute ) %>
<p class="help-block">
    <%= description %>
</p>
<% end %>

<% if notice = Profile.notice_for( attribute ) %>
    <p class="alert alert-info">
        <%= notice %>
    </p>
<% end %>

<% if warning = Profile.warning_for( attribute ) %>
    <p class="alert">
        <%= warning %>
    </p>
<% end %>

.system/arachni-ui-web/app/views/profiles/_import.html.erb
<div id="profile-import" class="modal hide fade" tabindex="-1" role="dialog">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
            &#10006;
        </button>
        <h3>Import profile:</h3>
    </div>

    <%= simple_form_for :profile, url: import_profiles_url, html: { multipart: true } do |f| %>
        <div class="modal-body">
            <%= f.error_notification %>
            <%= f.input :file, as: :file, label: false,
                        hint: 'Supported formats are: YAML, JSON, AFP (CLI-generated profiles)'
            %>
        </div>
        <div class="modal-footer">
            <%= f.button :submit, value: 'Import', class: 'btn btn-small btn-primary' %>
            <button class="btn btn-small" data-dismiss="modal" aria-hidden="true">Close</button>
        </div>
    <% end %>
</div>

.system/arachni-ui-web/app/views/profiles/_plugin_options.html.erb
<% disabled = false if local_assigns[:disabled].nil? %>

<%= render_options plugin_name, plugin_info, configuration, disabled %>

.system/arachni-ui-web/app/views/profiles/_subnav.html.erb
<% subnav scope: 'Scope <small>&mdash; Rules about which resources to include</small>',
          audit: 'Audit <small>&mdash; Fuzzing settings</small>',
          input: 'Input <small>&mdash; Sample values for inputs</small>',
          http: 'HTTP <small>&mdash; Network settings</small>',
          fingerprinting: 'Fingerprinting <small>&mdash; Platform identification</small>',
          checks: 'Checks <small>&mdash; Security checks</small>',
          plugins: 'Plugins <small>&mdash; Extra functionality</small>',
          browser_cluster: 'Browser cluster <small>&mdash; Browser-related options</small>',
          session: 'Session <small>&mdash; Session settings</small>' %>

.system/arachni-ui-web/app/views/profiles/_table.html.erb
<%
   params[:tab] ||= 'yours'
   active_tab     = params[:tab]
   opts           = params
%>

<ul class="nav nav-tabs" id="profile-table-tab"
    data-table-container="table-container">

    <% if @counts['yours'] == 0 %>
        <li class="disabled">
            <a href="#">
                <i class="icon-user"></i>
                Yours <small>[<%= @counts['yours'] %>]</small>
            </a>
        </li>
    <% else %>
        <li
        <% if active_tab == 'yours' %>
        class="active"
        <% end %>
        >

            <%= link_to profiles_path( opts.merge( 'tab' => 'yours' ) ),
                        onclick: 'loading();', remote: true do %>
                <i class="icon-user"></i>
                Yours <small>[<%= @counts['yours'] %>]</small>
            <% end %>
        </li>
    <% end %>

    <% if @counts['shared'] == 0 %>
        <li class="disabled">
            <a href="#">
                <i class="icon-share-alt"></i>
                Shared <small>[<%= @counts['shared'] %>]</small>
            </a>
        </li>
    <% else %>

        <li
        <% if active_tab == 'shared' %>
        class="active"
        <% end %>

        >
            <%= link_to profiles_path( opts.merge( 'tab' => 'shared' ) ),
                        onclick: 'loading();', remote: true do %>
                <i class="icon-share-alt"></i>
                Shared <small>[<%= @counts['shared'] %>]</small>
            <% end %>
        </li>
    <% end %>

    <% if @counts['global'] == 0 %>
        <li class="disabled">
            <a href="#">
                <i class="icon-globe"></i>
                Global <small>[<%= @counts['global'] %>]</small>
            </a>
        </li>
    <% else %>
        <li
        <% if active_tab == 'global' %>
        class="active"
        <% end %>
        >
            <%= link_to profiles_path( opts.merge( 'tab' => 'global' ) ),
                        onclick: 'loading();', remote: true do %>
                <i class="icon-globe"></i>
                Global <small>[<%= @counts['global'] %>]</small>
            <% end %>
        </li>
    <% end %>

    <% if current_user.admin? %>
        <% if @counts['others'] == 0 %>
            <li class="disabled">
                <a href="#">
                    <i class="icon-group"></i>
                    Others' <small>[<%= @counts['others'] %>]</small>
                </a>
            </li>
        <% else %>
            <li
            <% if active_tab == 'others' %>
            class="active"
            <% end %>
            >
                <%= link_to profiles_path( opts.merge( 'tab' => 'others' ) ),
                            onclick: 'loading();', remote: true do %>
                    <i class="icon-group"></i>
                    Others' <small>[<%= @counts['others'] %>]</small>
                <% end %>
            </li>
        <% end %>
    <% end %>

</ul>

<p class="muted">
    <%=
        case active_tab
            when 'yours'
                "You are seeing profiles you've created."
            when 'shared'
                "You are seeing profiles others have shared with you."
            when 'global'
                "You are seeing globally available profiles."
            when 'others'
                "You are seeing all others' profiles -- you can see them because you're an administrator."
        end
    %>
</p>

<% if profiles.any? %>
    <%= my_paginate profiles, remote: true %>

    <table class="table table-striped table-condensed">
        <thead>
        <tr>
            <% if active_tab == 'global' %>
            <th>
                Default?
            </th>
            <% end %>
            <th>
                Name
            </th>

            <% if active_tab != 'yours' %>
                <th>
                    Owner
                </th>
            <% end %>

            <th class="hidden-phone">
                Last update
            </th>
            <th class="hidden-phone">
                Created at
            </th>
        </tr>
        </thead>
        <% profiles.each do |profile| %>
            <tr>
                <% if active_tab == 'global' %>
                    <td>
                        <%= simple_form_for profile,
                                           url: make_default_profile_path( profile, opts ),
                                           method: :patch, remote: true,
                                           html: { onsubmit: 'loading();' } do %>
                            <input type="radio"
                                   class="make-default"
                                    onclick="$(this).submit()"
                                   <%= 'checked="checked"'.html_safe if profile.default? %>
                                   <%= 'disabled' if !current_user.admin? %>
                            >
                        <% end %>
                    </td>
                <% end %>

                <td><%= profile.name %></td>

                <% if active_tab != 'yours' %>
                    <td>
                        <% if profile.owner == current_user %>
                            <span class="label">You</span>
                        <% else %>
                            <%= link_to profile.owner, user_path( profile.owner ) %>
                    <% end %>
                    </td>
                <% end %>

                <td class="hidden-phone"><%= l profile.updated_at %></td>
                <td class="hidden-phone"><%= l profile.created_at %></td>
                <td>
                    <% if can? :read, profile %>
                        <%= link_to profile, title: 'Show', class: 'btn btn-small btn-info' do %>
                            <i class="icon-eye-open icon-muted"></i>
                        <% end %>
                    <% end %>

                    <%= render partial: 'actions', locals: { profile: profile } %>
                </td>
            </tr>
            <tr>
                <td class="description" colspan='5'>
                    <blockquote><%= profile.html_description_excerpt %></blockquote>
                </td>
            </tr>
        <% end %>
<% else %>
    <p class="alert alert-info">
        No such profiles.
    </p>
<% end %>
</table>

.system/arachni-ui-web/app/views/profiles/_table.js.erb
$('#profiles #table').html( "<%= escape_javascript( render partial: 'table', formats: :html, locals: { profiles: @profiles } ) %>" )

.system/arachni-ui-web/app/views/profiles/edit.html.erb
<% title "Editing #{@profile.name}" %>

<% breadcrumb_add 'Profiles', profiles_path %>

<% render partial: 'subnav' %>

<div class="page-header">
    <h1>Editing '<%= @profile.name %>' profile</h1>
</div>

<div id='profiles'>
<%= render 'form' %>
</div>

.system/arachni-ui-web/app/views/profiles/index.html.erb
<% title 'Profiles' %>

<div class="page-header">
    <h1>Profiles</h1>

    <div class="lead">
        Maintain and use scan configuration profiles to make your job easier.
    </div>

    <p class="muted">
        Hint: It is best to use custom, per-scan, profiles when needing to specify special
        headers or session cookies so that you'll be able to update them when
        repeating scans.
    </p>
</div>

<% if can? :edit, Profile %>
<p>
    <%= link_to new_profile_path, class: 'btn btn-primary' do %>
        <i class="icon-plus"></i> New Profile
    <% end %>

    <a href="#profile-import" title="Import a profile"
       role="button" class="btn btn-inverse" data-toggle="modal">
        <i class="icon-upload-alt"></i> Import
    </a>
</p>
<% end %>

<%= render partial: 'import' %>

<div id="profiles">
    <div id="table">
        <%= render partial: 'table', formats: :html, locals: { profiles: @profiles } %>
    </div>
</div>

.system/arachni-ui-web/app/views/profiles/new.html.erb
<% breadcrumb_add 'Profiles', profiles_path %>
<% breadcrumb_add 'New', new_profile_path %>
<% render partial: 'subnav' %>

<div class="page-header">
    <h1>Create a profile</h1>

    <div class="lead">
        Create a new profile from a plethora of options but please pay attention
        to their description and assorted notices.
    </div>
</div>

<div id='profiles'>
<%= render 'form' %>
</div>

<%= link_to 'Back', profiles_path %>

.system/arachni-ui-web/app/views/profiles/show.html.erb
<% title @profile.name %>

<% breadcrumb_add 'Profiles', profiles_path %>
<% render partial: 'subnav' %>

<% add_to_affixed_sidebar do %>
    <%= render partial: 'actions', locals: { profile: @profile } %>
<% end %>

<div id='profiles'>
    <%= render @profile %>
</div>