.system/arachni-ui-web/config/routes.rb
=begin
    Copyright 2013-2022 Ecsypno <http://www.ecsypno.com>

    This file is part of the Arachni WebUI project and is subject to
    redistribution and commercial restrictions. Please see the Arachni WebUI
    web site for more information on licensing and terms of use.
=end

ArachniWebui::Application.routes.draw do
    resources :settings

    resources :notifications, only: [:mark_all_read, :destroy] do
        patch :mark_read, on: :collection
    end

    resources :dispatchers do
        patch :make_default, on: :member
        patch :share,        on: :member
    end

    scope 'scans' do
        resources :scan_groups, path: 'groups',
                  only: [ :new, :edit, :create, :update, :destroy ]
    end

    resources :scans do
        resources :comments
        resources :issues, only: [ :index, :show, :update ] do
            resources :comments
        end

        post :repeat,   on: :member

        patch :update_memberships,    on: :member
        patch :suspend,  on: :member
        patch :restore,  on: :member
        patch :share,    on: :member
        patch :pause,    on: :member
        patch :resume,   on: :member
        patch :abort,    on: :member

        post  :import,   on: :collection

        patch :suspend,  on: :collection, to: :suspend_all
        patch :pause,    on: :collection, to: :pause_all
        patch :resume,   on: :collection, to: :resume_all
        patch :abort,    on: :collection, to: :abort_all

        get :new_revision, on: :member
        get :report,   on: :member
        get :comments, on: :member
        get :errors,   on: :member
        get :count,    on: :collection
        get :schedule, on: :collection
    end

    resources :profiles do
        post  :import,       on: :collection
        patch :make_default, on: :member
        patch :share,        on: :member
        get   :copy,         on: :member
    end

    get '/navigation', :to => 'home#navigation'
    get '/welcome',    :to => 'home#welcome'

    root to: 'home#index'

    devise_for :users, :skip => [:registrations], path_prefix: 'd'
    as :user do
        get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
        patch 'users' => 'devise/registrations#update', as: 'user_registration'
    end
    resources :users
end

.system/arachni-ui-web/app/helpers/scans_helper.rb
=begin
    Copyright 2013-2022 Ecsypno <http://www.ecsypno.com>

    This file is part of the Arachni WebUI project and is subject to
    redistribution and commercial restrictions. Please see the Arachni WebUI
    web site for more information on licensing and terms of use.
=end

module ScansHelper

    def prepare_tables_data
        params[:filter_finished]  ||= 'yours'
        params[:filter_active]    ||= 'yours'
        params[:filter_suspended] ||= 'yours'

        @counts = {
            active: {},
            finished: {},
            suspended: {}
        }
        %w(yours shared others).each do |type|
            begin
                @counts[:active][type] = scan_filter( type ).active.count
                @counts[:active]['total'] ||= 0
                @counts[:active]['total']  += @counts[:active][type]

                @counts[:finished][type] = scan_filter( type ).finished.count
                @counts[:finished]['total'] ||= 0
                @counts[:finished]['total']  += @counts[:finished][type]

                @counts[:suspended][type] = scan_filter( type ).suspended.count
                @counts[:suspended]['total'] ||= 0
                @counts[:suspended]['total']  += @counts[:suspended][type]
            rescue
            end
        end

        @active_scans = scan_filter( params[:filter_active] ).active.
                            page( params[:active_page] ).
                            per( HardSettings.active_scan_pagination_entries ).
                            order( 'id DESC' )

        @finished_scans = scan_filter( params[:filter_finished] ).roots.finished.
                            page( params[:finished_page] ).
                            per( HardSettings.finished_scan_pagination_entries ).
                            order( 'id DESC' )

        @suspended_scans = scan_filter( params[:filter_suspended] ).roots.suspended.
                            page( params[:suspended_page] ).
                            per( HardSettings.finished_scan_pagination_entries ).
                            order( 'id DESC' )
    end

    def prepare_schedule_data
        params[:filter] ||= 'yours'

        @counts = {}
        %w(yours shared others).each do |type|
            begin
                @counts[type] = scan_filter( type ).scheduled.count

                @counts['total'] ||= 0
                @counts['total']  += @counts[type]
            rescue => e
                ap e
                ap e.backtrace
            end
        end

        @scans = scan_filter( params[:filter] ).scheduled.
            page( params[:active_page] ).
            per( HardSettings.scheduled_scan_pagination_entries ).
            order( 'id DESC' )
    end

    def scan_filter( filter )
        filter ||= 'yours'

        group_scans =   if (group_id = params[:group_id].to_i) > 0
                            if current_user.admin?
                                if (@group = ScanGroup.find_by_id( params[:group_id] ))
                                    @group.scans
                                else
                                    current_user.scans
                                end
                            else
                                @group = current_user.scan_groups.find_by_id( params[:group_id] )

                                if @group
                                    @group.scans
                                else
                                    current_user.scans
                                end
                            end
                        else
                            current_user.scans
                        end

        case filter
            when 'yours'
                group_scans.where( owner_id: current_user.id )

            when 'shared'
                s = group_scans.where( 'owner_id != ?', current_user.id )

                if current_user.admin?
                    s.where( 'id in (?)', current_user.scans.pluck( :id ) )
                else
                    s
                end

            when 'others'
                raise 'Unauthorised!' if !current_user.admin?

                ids = group_scans.where( 'owner_id != ?', current_user.id ).
                        where( 'id in (?)', current_user.scans.pluck( :id ) ) +
                    group_scans.select( :id ).
                        where( owner_id: current_user.id )

                rest_ids = if group_id
                               group_scans
                           else
                               Scan
                           end.select( :id )

                Scan.where( id: rest_ids - ids )
        end
    end

    def issues_to_graph_data( issues )
        graph_data = {
            severities:       {
                Arachni::Severity::HIGH.to_sym          => 0,
                Arachni::Severity::MEDIUM.to_sym        => 0,
                Arachni::Severity::LOW.to_sym           => 0,
                Arachni::Severity::INFORMATIONAL.to_sym => 0
            },
            issues:           {},
            elements:         {
                Arachni::Element::Form.type              => 0,
                Arachni::Element::Form::DOM.type         => 0,
                Arachni::Element::Link.type              => 0,
                Arachni::Element::Link::DOM.type         => 0,
                Arachni::Element::Cookie.type            => 0,
                Arachni::Element::Cookie::DOM.type       => 0,
                Arachni::Element::Header.type            => 0,
                Arachni::Element::LinkTemplate.type      => 0,
                Arachni::Element::LinkTemplate::DOM.type => 0,
                Arachni::Element::GenericDOM.type        => 0,
                Arachni::Element::XML.type               => 0,
                Arachni::Element::JSON.type              => 0,
                Arachni::Element::UIForm.type            => 0,
                Arachni::Element::UIForm::DOM.type       => 0,
                Arachni::Element::UIInput.type           => 0,
                Arachni::Element::UIInput::DOM.type      => 0,
                Arachni::Element::Body.type              => 0,
                Arachni::Element::Path.type              => 0,
                Arachni::Element::Server.type            => 0
            }
        }

        total_severities = 0
        total_elements   = 0

        issues.each.with_index do |issue, i|
            graph_data[:severities][issue.severity.downcase.to_sym] += 1
            total_severities += 1

            graph_data[:issues][issue.name] ||= 0
            graph_data[:issues][issue.name] += 1

            graph_data[:elements][issue.vector_type.to_sym] += 1
            total_elements += 1
        end

        graph_data
    end

    def response_times_to_alert( time )
        time = time.to_f

        if time >= 0.7
            [ 'alert-error',
              'The server takes too long to respond to the scan requests,' +
                  ' this will severely diminish performance.']
        elsif (0.35..0.7).include?( time )
            [ 'alert-warning',
              'Server response times could be better but nothing to worry about yet.' ]
        else
            [ 'alert-success',
              'Server response times are excellent.' ]
        end
    end

    def concurrent_requests_to_alert( request_count, max )
        max = max.to_i
        request_count = request_count.to_i

        if request_count >= max
            [ 'alert-success',
              'HTTP request concurrency is operating at the allowed maximum.']
        elsif ((max/2)..max).include?( request_count )
            [ 'alert-warning',
              "HTTP request concurrency had to be throttled down (from the " +
                  "maximum of #{max}) due to high server response times, " +
                  'nothing to worry about yet though.' ]
        else
            [ 'alert-error',
              'HTTP request concurrency has been drastically throttled down ' +
                  "(from the maximum of #{max}) due to very high server" +
                  " response times, this will severely decrease performance."]
        end
    end
end

.system/arachni-ui-web/app/views/scans/_import.html.erb
<div id="scan-import" class="modal hide fade" tabindex="-1" role="dialog">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
            &#10006;
        </button>
        <h3>Import scan report:</h3>
    </div>

    <%= simple_form_for :scan, url: import_scans_path, html: { multipart: true } do |f| %>
        <div class="modal-body">
            <%= f.error_notification %>
            <%= f.input :file, as: :file, label: false,
                        hint: 'Please specify an AFR file.'
            %>
        </div>
        <div class="modal-footer">
            <%= f.button :submit, value: 'Import', class: 'btn btn-small btn-primary' %>
            <button class="btn btn-small" data-dismiss="modal" aria-hidden="true">Close</button>
        </div>
    <% end %>
</div>

.system/arachni-ui-web/app/views/scans/_scan_sidebar.html.erb
<ul class="nav nav-list">
    <li class="nav-header">
        Toggle visibility of
    </li>

    <li id="comments-link-container">
        <a class="toggle-comments" data-toggle="collapse"
           href="#comments">
            <i class="icon-comments"></i>

                    <span title="The scan has <%= pluralize @scan.comments.size, 'comment' %>."
                          class="label hide total-comments-counter">
                        <%= @scan.comments.size %>
                    </span>

                    <span title="The scan has new comments."
                          class="hide label label-info new-comments-counter">
                    </span>

            Comments
        </a>
    </li>

    <% if @scan.running? %>
    <li id="toggle-statistics">
        <a href="#statistics" data-toggle="collapse"
           title="Toggle statistics visibility" role="button">
            <i class="icon-list-alt"></i>

            Statistics
        </a>
    </li>
    <% end %>
</ul>

<% if @scan.root_revision.has_revisions? %>
    <div id="revisions-nav-list">
        <%= render 'revisions_nav_list' %>
    </div>
<% end %>

<ul class="nav nav-list">
    <li class="divider"></li>

    <li class="nav-header">
        Actions
    </li>

    <% if User.count > 1 && can?( :share, @scan ) %>
        <li>
            <a href="#shareScan<%= @scan.id %>" title="Share scan"
               role="button" data-toggle="modal">
                <i class="icon-share"></i>

                <% if (shared_with = @scan.users.size - 1) > 0 %>
                      <span title="Shared with <%= pluralize shared_with, 'more user' %>."
                            class="label"><%= shared_with %></span>
                <% end %>

                Share
            </a>

            <%= render partial: 'shared/share_form', locals: { model: @scan, nodisplay: true } %>
        </li>
    <% end %>

    <% if !@scan.suspended? && !@scan.finished? && can?( :update, @scan ) %>
        <li>
            <a href="#updateScanSchedule_<%= @scan.id %>"
               title="Update schedule"
               role="button" data-toggle="modal">
                <i class="icon-calendar"></i>
                Edit schedule
            </a>

            <%= render partial: 'scan_schedule_form', locals: { scan: @scan, nodisplay: true } %>
        </li>
    <% end %>

    <% if current_user.scan_groups.any? && can?( :update, @scan ) %>
        <li>
            <a href="#updateScanGroup_<%= @scan.id %>"
               title="Update group memberships"
               role="button" data-toggle="modal">
                <i class="icon-folder-close-alt"></i>
                Edit group memberships
            </a>

            <%= render partial: 'scan_group_form', locals: { scan: @scan, nodisplay: true } %>
        </li>
    <% end %>

    <% if can?( :update, @scan ) %>
        <li>
            <a href="<%= edit_scan_path @scan %>"
               title="Edit this scan's details"
               role="button">
                <i class="icon-edit"></i>
                Full edit
            </a>
        </li>
    <% end %>

    <% if !@scan.suspended? && @scan.finished? && !@scan.overview? && @scan.report %>
        <li id="download-report">
            <i class="icon-download-alt"></i>
            Download report as:

            <%
               reports_links = reports_with_outfile.map do |shortname, (name, desc)|
                   link_to name, report_scan_path( format: shortname ),
                           rel: 'tooltip', title:  desc, data: { 'no-turbolink' => true }
               end
            %>

            <ul class="nav nav-list">
                <% reports_links.each do |l| %>
                    <li>
                        <%= l %>
                    </li>
                <% end %>
                <li>
                    <%=
                        link_to 'AFR', report_scan_path( format: 'afr' ),
                                rel: 'tooltip', title:  'Arachni Framework Report',
                                data: { 'no-turbolink' => true }
                    %>
                </li>
            </ul>
        </li>
    <% end %>
</ul>

.system/arachni-ui-web/app/views/scans/_show_active.html.erb
<% if @scan.schedule.stop_after %>
    <% if !@scan.timed_out? %>
        <div class="row-fluid">
          <% if @scan.scanning? %>
            <div class="span12 alert alert-info">
                <i class="icon-calendar"></i>

                Will <%= @scan.schedule.stop_suspend? ? 'suspend' : 'abort' %> in
                <%= Arachni::Utilities.seconds_to_hms @scan.schedule.stop_after - @scan.runtime %>.
            </div>
            <% elsif @scan.schedule.stop_suspend? %>

              <div class="span12 alert alert-warning">
                <i class="icon-calendar"></i>

                Configured to be suspended in
                <%= Arachni::Utilities.seconds_to_hms @scan.schedule.stop_after - @scan.runtime %>
                but won't do so unless the scan state is restored to "Scanning".
              </div>

        <% end %>
        </div>
    <% elsif @scan.schedule.stop_suspend? && !@scan.scanning? %>
        <div class="span12 alert alert-warning">
          <i class="icon-calendar"></i>

          The scan will suspend as soon as its state is restored to "Scanning".
        </div>
    <% end %>
<% end %>

<div class="row-fluid">
  <div class="span2">
    <div class="row-fluid">
      <div class="span12">
        <%
           status_label = if @scan.paused?
                              'label-warning'
                          elsif @scan.completed?
                              'label-success'
                          elsif @scan.aborted?
                              'label-important'
                          else
                              'label-info'
                          end
        %>
        <span class="label <%= status_label %>">
            <%= @scan.status.to_s.capitalize %>
        </span>
      </div>
    </div>

    <div class="row-fluid">
      <div class="span12">
        <% if can? :pause, @scan %>
            <% if @scan.paused? %>
                <%= link_to resume_scan_path(@scan),
                            remote: true,
                            title:  'Resume scan', method: :patch, class: 'btn btn-small btn-success',
                            data:   { confirm: 'Are you sure you want to resume the scan?' } do %>
                    <i class=" icon-play-circle"></i>
                <% end %>

            <% else %>
                <%= link_to pause_scan_path(@scan),
                            remote: true,
                            title:  'Pause scan', method: :patch, class: 'btn btn-small btn-warning',
                            data:   { confirm: 'Are you sure you want to pause the scan?' } do %>
                    <i class="icon-pause"></i>
                <% end %>
            <% end %>
        <% end %>

        <% if @scan.scanning? && @scan.spawns == 0 && can?( :suspend, @scan ) %>
            <%= link_to suspend_scan_path(@scan),
                        remote: true,
                        title:  'Suspend scan', method: :patch, class: 'btn btn-small',
                        data:   { confirm: 'Are you sure you want to suspend the scan?' } do %>
                <i class="icon-eject"></i>
            <% end %>
        <% end %>

        <% if can? :abort, @scan %>
            <%= link_to abort_scan_path(@scan),
                        remote: true,
                        title:  'Abort scan', method: :patch, class: 'btn btn-small btn-danger',
                        data:   { confirm: 'Are you sure you want to abort the scan?' } do %>
                <i class="icon-stop"></i>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="span10">
    <div class="row-fluid">

      <div class="span12 alert alert-info">
        <strong>Currently auditing:</strong>

        <ul>
          <% [@scan.statistics[:current_page] || @scan.statistics[:current_pages]].
                     flatten.compact.each do |url| %>
              <li>
                <% if url.to_s.empty? %>
                    <em>Instance idle, waiting for workload.</em>
                <% else %>
                    <%= link_to url, url %>
                <% end %>
              </li>
          <% end %>
        </ul>

        <% if @scan.messages.any? %>
            <strong>Messages:</strong>

            <ul>
            <% @scan.messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

      </div>
    </div>
  </div>
</div>

<hr/>

<div class="row-fluid collapse" id="statistics">
  <div class="span12">
      <table class="table table-condensed">
        <thead>
        <tr>
            <th>Pages discovered</th>
            <td><%= @scan.statistics[:found_pages] %></td>

            <th class="hidden-phone">Requests performed</th>
            <td class="hidden-phone"><%= @scan.statistics[:http][:request_count] %></td>

            <th>Requests per second</th>
            <td><%= '%.2f' % @scan.statistics[:http][:total_responses_per_second].to_f %></td>

            <%
               max_concurrency_class, info = concurrent_requests_to_alert(
                       @scan.statistics[:http][:max_concurrency],
                       @scan.profile.http_request_concurrency * @scan.instance_count
               )
            %>
            <th>Request concurrency</th>
            <td class='alert <%= max_concurrency_class %>'>
                <abbr title="<%= info %>">
                    <%= @scan.statistics[:http][:max_concurrency].to_i %>
                </abbr>
            </td>
        </tr>
        <tr>

            <th class="hidden-phone">Running for</th>
            <td class="hidden-phone"><%= Arachni::Utilities.seconds_to_hms @scan.runtime %></td>

            <th class="hidden-phone">Responses received</th>
            <td class="hidden-phone"><%= @scan.statistics[:http][:response_count] %> </td>

            <th class="hidden-phone">Timed out requests</th>
            <td class="hidden-phone"><%= @scan.statistics[:http][:time_out_count] %></td>

            <%
               curr_res_time_class, info = response_times_to_alert(@scan.statistics[:http][:total_average_response_time])
            %>
            <th>Response times</th>
            <td class="alert <%= curr_res_time_class %>">
                <abbr data-placement="bottom" title="<%= info %>">
                    <%= '%.3f' % @scan.statistics[:http][:total_average_response_time].to_f %>
                    s
                </abbr>
            </td>
        </tr>
        </thead>
      </table>
  </div>
</div>

<script type="text/javascript">
    window.setupScanCallbacks();

    $('#issues').show();
    $('#scan-sidebar').show('slow');
    $('li#toggle-statistics').fadeIn('slow');
    $('li#toggle-charts').fadeIn('slow');
    $('li#download-report').hide();
</script>

.system/arachni-ui-web/app/views/scans/_table.html.erb
<%
   treat_as_running = local_assigns[:treat_as_running].nil? ? true : false

   show_revision_legend, show_error_legend, show_aborted_legend = false

   filter = "filter_#{type}"
   opts = params.dup
   opts.delete( :format )

   yours = (params[filter] == 'yours')
%>

<ul class="nav nav-tabs" id="scan-table-tab"
    data-table-container="<%= type %>-table-container">

    <% if @counts[type.to_sym]['yours'] == 0 %>
        <li class="disabled">
            <a href="#">
                <i class="icon-user"></i>
                Yours <small>[<%= @counts[type.to_sym]['yours'] %>]</small>
            </a>
        </li>
    <% else %>
    <li
        <% if yours %>
           class="active"
        <% end %>
        >

        <%= link_to scans_path( opts.merge( filter => 'yours' ) ),
                    onclick: 'loading();', remote: true do %>
            <i class="icon-user"></i>
            Yours <small>[<%= @counts[type.to_sym]['yours'] %>]</small>
        <% end %>
    </li>
    <% end %>

    <% if @counts[type.to_sym]['shared'] == 0 %>
        <li class="disabled">
            <a href="#">
                <i class="icon-share-alt"></i>
                Shared <small>[<%= @counts[type.to_sym]['shared'] %>]</small>
            </a>
        </li>
    <% else %>

    <li
        <% if params[filter] == 'shared' %>
        class="active"
        <% end %>

        >
        <%= link_to scans_path( opts.merge( filter => 'shared' ) ),
                    onclick: 'loading();', remote: true do %>
            <i class="icon-share-alt"></i>
            Shared <small>[<%= @counts[type.to_sym]['shared'] %>]</small>
            <% end %>
        </li>
    <% end %>

    <% if current_user.admin? %>

        <% if @counts[type.to_sym]['others'] == 0 %>
            <li class="disabled">
                <a href="#">
                    <i class="icon-group"></i>
                    Others' <small>[<%= @counts[type.to_sym]['others'] %>]</small>
                </a>
            </li>
        <% else %>
            <li
            <% if params[filter] == 'others' %>
            class="active"
            <% end %>
            >
                <%= link_to scans_path( opts.merge( filter => 'others' ) ),
                            onclick: 'loading();', remote: true do %>
                    <i class="icon-group"></i>
                    Others' <small>[<%= @counts[type.to_sym]['others'] %>]</small>
            <% end %>
            </li>
        <% end %>
    <% end %>
</ul>

<% if scans.any? %>

<div id="<%= type %>-table-container">

    <% if treat_as_running && params[filter] =='yours' %>
        <% if current_user.own_scans.paused.any? %>
            <%= link_to resume_scans_path, title: 'Resume all scans',
                        method: :patch, class: 'btn btn-small btn-success',
                        remote: true,
                        data: { confirm: 'Are you sure you want to resume all scans?' } do %>
                <i class="icon-play-circle"></i>
            <% end %>
        <% end %>

        <% if current_user.own_scans.running.any? %>
            <%= link_to pause_scans_path, title: 'Pause all scans',
                        method: :patch, class: 'btn btn-small btn-warning',
                        remote: true,
                        data: { confirm: 'Are you sure you want to pause all scans?' } do %>
                <i class="icon-pause"></i>
            <% end %>
        <% end %>

        <% if current_user.own_scans.active.any? %>
            <%= link_to abort_scans_path, title: 'Abort all scans',
                        method: :patch, class: 'btn btn-small btn-danger',
                        remote: true,
                        data: { confirm: 'Are you sure you want to abort all scans?' } do %>
                <i class="icon-stop"></i>
            <% end %>
        <% end %>
    <% end %>

    <p class="muted">
    <%=
        case params[filter]
            when 'yours'
                "You are seeing scans you've started."
            when 'shared'
                "You are seeing scans others have shared with you."
            when 'others'
                "You are seeing all others' scans -- you can see them because you're an administrator."
        end
    %>
    </p>

    <%= my_paginate scans, remote: true, param_name: type + '_page' %>

    <table class="table table-striped table-hover table-condensed">
        <%= render partial: 'table_headings', locals: {
                treat_as_running:   treat_as_running,
                yours:              yours,
                type:               type
        } %>

        <% scans.each do |scan| %>
            <% next if !treat_as_running && scan.revision? %>

            <tr <%= if scan.aborted?
                        show_aborted_legend = true
                    elsif scan.error?
                        show_error_legend = true
                    end
                %>
            >

            <%= render partial: 'table_row',
                       locals: { scan: scan, treat_as_running: treat_as_running, type: type } %>
        <% end %>
    </table>

    <% if show_aborted_legend || show_error_legend %>
        <div class="alert alert-info">
            <ul>
                <% if show_revision_legend %>
                    <li>Blue rows indicate repeated/revised scans.</li>
                <% end %>

                <% if show_aborted_legend %>
                <li>Yellow rows indicate aborted scans.</li>
                <% end %>

                <% if show_error_legend %>
                <li>Red rows indicate scans which have stopped due to a fatal
                    error (i.e. the scan Instance suddenly died).</li>
                <% end %>
            </ul>
        </div>
    <% end %>

</div>
    <% else %>
    <p class="alert alert-info">
        There are no scans in the '<%= params[filter].to_s.capitalize %>'
        category at the moment.
    </p>
<% end %>

<script type="text/javascript">
    updatePage();
</script>

.system/arachni-ui-web/app/views/scans/show.html.erb
<% title @scan.url %>
<% breadcrumb_add 'Scans', scans_path %>

<% add_to_sidebar do %>
    <div id="scan-sidebar" class="hide">
        <%= render partial: 'scan_sidebar' %>
    </div>
<% end %>

<div id="scans">
    <div class="page-header">
        <% if @scan.owner != current_user %>
            <span class="pull-right muted">
                Started by <%= link_to @scan.owner, user_path( @scan.owner ) %>
            </span>
        <% end %>

        <% purl = @scan.parsed_url %>
        <h1>
            <%= "#{purl.scheme}://#{purl.host}" %><%= ":#{purl.port}" if purl.port %><small><%= "#{purl.path}#{!purl.query.to_s.empty? ? "?#{purl.query}" : nil}" %></small>
        </h1>

        <div id="editable-description">
            <%= render partial: 'editable_description' %>
        </div>
    </div>

    <div class="visible-phone pull-left">
        <%= render partial: 'shared/share_form', locals: { model: @scan } %>
        <%= render partial: 'scan_group_form', locals: { scan: @scan } %>
        <%= render partial: 'scan_schedule_form', locals: { scan: @scan } %>
    </div>

    <div class="visible-phone">
        <a class="toggle-comments btn btn-small" data-toggle="collapse"
           href="#comments">
            <i class="icon-comments"></i>

            <% if @scan.comments.any? %>
                <span title="The scan has <%= pluralize @scan.comments.size, 'comment' %>."
                      class="label total-comments-counter"><%= @scan.comments.size %></span>
            <% end %>

            <span title="The scan has new comments."
                  class="hide label label-info new-comments-counter"></span>

            Toggle comments
        </a>

        <hr/>
    </div>

    <div id="comments" class="accordion-body collapse">
        <%= render partial: 'comments' %>
    </div>

    <div id="error-messages-container" <%= 'class="hide"'.html_safe if @scan.error_messages.empty? %> >
        <p class="alert alert-error">
            <i class="icon-exclamation-sign"></i>

            This scan has the logged the following
            <%= link_to 'errors', errors_scan_path( @scan, format: :txt ) %>
            (if something looks like a bug feel free to
            <a target="_blank" href="https://github.com/Arachni/arachni/issues">report</a> it):
        </p>

        <pre id="error-messages"></pre>
    </div>

    <div id="scan">
      <% if @scan.suspended? %>
          <%= render 'show_suspended' %>
      <% else %>
        <%= render @scan.active? ? 'show_active' : 'show_inactive' %>
      <% end %>
    </div>

    <div class="row-fluid">
        <div class="span12" id='issues'>
            <%= render partial: 'issues/table.html', locals: { url_method_type: :scan_path } %>
        </div>
    </div>

</div>

<% if Settings.scan_auto_refresh? %>
    <div id="updater"
         data-refresh-url="<%= scan_path( @scan, params.merge( format: :js ) ) %>"
         data-refresh-rate="<%= HardSettings.scan_refresh_rate %>"
         data-refresh-type="js">
    </div>
<% end %>