.system/arachni-ui-web/config/routes.rb
=begin
    Copyright 2013-2022 Ecsypno <http://www.ecsypno.com>

    This file is part of the Arachni WebUI project and is subject to
    redistribution and commercial restrictions. Please see the Arachni WebUI
    web site for more information on licensing and terms of use.
=end

ArachniWebui::Application.routes.draw do
    resources :settings

    resources :notifications, only: [:mark_all_read, :destroy] do
        patch :mark_read, on: :collection
    end

    resources :dispatchers do
        patch :make_default, on: :member
        patch :share,        on: :member
    end

    scope 'scans' do
        resources :scan_groups, path: 'groups',
                  only: [ :new, :edit, :create, :update, :destroy ]
    end

    resources :scans do
        resources :comments
        resources :issues, only: [ :index, :show, :update ] do
            resources :comments
        end

        post :repeat,   on: :member

        patch :update_memberships,    on: :member
        patch :suspend,  on: :member
        patch :restore,  on: :member
        patch :share,    on: :member
        patch :pause,    on: :member
        patch :resume,   on: :member
        patch :abort,    on: :member

        post  :import,   on: :collection

        patch :suspend,  on: :collection, to: :suspend_all
        patch :pause,    on: :collection, to: :pause_all
        patch :resume,   on: :collection, to: :resume_all
        patch :abort,    on: :collection, to: :abort_all

        get :new_revision, on: :member
        get :report,   on: :member
        get :comments, on: :member
        get :errors,   on: :member
        get :count,    on: :collection
        get :schedule, on: :collection
    end

    resources :profiles do
        post  :import,       on: :collection
        patch :make_default, on: :member
        patch :share,        on: :member
        get   :copy,         on: :member
    end

    get '/navigation', :to => 'home#navigation'
    get '/welcome',    :to => 'home#welcome'

    root to: 'home#index'

    devise_for :users, :skip => [:registrations], path_prefix: 'd'
    as :user do
        get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
        patch 'users' => 'devise/registrations#update', as: 'user_registration'
    end
    resources :users
end

.system/arachni-ui-web/app/models/issue.rb
=begin
    Copyright 2013-2022 Ecsypno <http://www.ecsypno.com>

    This file is part of the Arachni WebUI project and is subject to
    redistribution and commercial restrictions. Please see the Arachni WebUI
    web site for more information on licensing and terms of use.
=end

class Issue < ActiveRecord::Base
    include Extensions::Notifier

    belongs_to :scan

    has_many :comments, as: :commentable, dependent: :destroy

    validate :validate_review_options
    validate :validate_verification_steps
    validate :validate_remediation_steps

    validates_uniqueness_of :digest, scope: :scan_id

    serialize :references,      Hash
    serialize :remarks,         Hash
    serialize :tags,            Array
    serialize :dom_transitions, Array
    serialize :headers,         Hash
    serialize :vector_inputs,   Hash

    FRAMEWORK_ISSUE_MAP = {
        name:            nil,
        description:     nil,
        references:      nil,
        remedy_code:     nil,
        remedy_guidance: nil,
        digest:          nil,
        cwe:             nil,
        tags:            nil,
        vector_type:     { vector:   { class: :type } },
        vector_html:     { vector:   :html },
        url:             { vector:   :action },
        severity:        { severity: { to_s: :capitalize } }
    }

    FRAMEWORK_ISSUE_VARIATION_MAP = {
        signature:             :signature,
        proof:                 :proof,
        requires_verification: :untrusted?,
        remarks:               :remarks,
        dom_transitions:       { page:     { dom: :transitions } },
        dom_body:              { page:     :body },
        http_method:           { vector:   :http_method },
        vector_inputs:         { vector:   :inputs },
        vector_name:           { vector:   :affected_input_name },
        seed:                  { vector:   :affected_input_value },
        response_body:         { response: :body },
        response:              { response: :to_s },
        request:               { request:  :to_s }
    }

    ORDERED_SEVERITIES = [
        Arachni::Issue::Severity::HIGH.to_s.capitalize,
        Arachni::Issue::Severity::MEDIUM.to_s.capitalize,
        Arachni::Issue::Severity::LOW.to_s.capitalize,
        Arachni::Issue::Severity::INFORMATIONAL.to_s.capitalize
    ]

    PROTECTED = [:remediation_steps, :verification_steps, :false_positive, :fixed]

    scope :fixed, -> { where fixed: true }
    scope :light, -> { select( column_names - %w(response_body references) ) }
    scope :false_positives, -> { where( 'false_positive = ?', true ) }
    scope :verified, -> do
        where( 'requires_verification = ? AND verified = ? AND ' +
                   'false_positive = ? AND fixed = ?', true, true, false, false )
    end
    scope :pending_verification, -> do
        where( 'requires_verification = ? AND verified = ? AND '+
                   ' false_positive = ? AND fixed = ?', true, false, false, false )
    end

    def self.order_by_severity
        ret = 'CASE'
        ORDERED_SEVERITIES.each_with_index do |p, i|
            ret << " WHEN severity = '#{p}' THEN #{i}"
        end
        ret << ' END'
    end
    scope :by_severity, -> { order order_by_severity }
    default_scope { by_severity }

    def timeline
        Notification.where( model_id: id, model_type: self.class.to_s,
                            user_id: scan.owner_id ).order( 'id desc' )
    end

    def id_name
        name#.parameterize
    end

    def url
        return nil if super.to_s.empty?
        super
    end

    def seed
        return nil if super.to_s.empty?
        super
    end

    def proof
        return nil if super.to_s.empty?
        super
    end

    def response_body
        return nil if super.to_s.empty?
        super
    end

    def signature
        return nil if super.to_s.empty?
        super
    end

    def verified?
        super && !false_positive?
    end

    def pending_verification?
        requires_verification? && !verified? && !false_positive? && !fixed?
    end

    def pending_review?
        !verified && !false_positive && !requires_verification && !fixed?
    end

    def requires_verification_and_verified?
        requires_verification? && verified? && !false_positive?
    end

    def has_verification_steps?
        !verification_steps.to_s.empty?
    end

    def has_remediation_steps?
        !remediation_steps.to_s.empty?
    end

    def dom_body_contains_proof?
        proof && dom_body && dom_body.include?( proof )
    end

    def response_contains_proof?
        proof && response && response.include?( proof )
    end

    def to_s
        s = "#{name} in #{vector_type.capitalize}"
        s << " input '#{vector_name}'" if vector_name
        s
    end

    def cwe_url
        return if cwe.to_s.empty?
        "http://cwe.mitre.org/data/definitions/#{cwe}.html"
    end

    def subscribers
        scan.subscribers
    end

    def family
        [scan, self]
    end

    def self.describe_notification( action )
        case action
            when :destroy
                'was deleted'
            when :update, :reviewed
                'was reviewed'
            when :verified
                'was verified'
            when :fixed
                'has an updated fixed state'
            when :false_positive
                'has an updated false positive state'
            when :requires_verification
                'has an updated manual verification state'
            when :verification_steps
                'has updated verification steps'
            when :remediation_steps
                'has updated remediation steps'
            when :commented
                'has a new comment'
        end
    end

    def self.create_from_framework_issue( issue )
        create translate_framework_issue( issue )
    end

    def self.update_from_framework_issue( issue, update_only = [] )
        h = translate_framework_issue( issue )

        return if !(i = where( digest: issue.digest.to_s ).first)

        h.delete( :requires_verification ) if i.requires_verification?

        h.reject! { |k| !update_only.include? k } if update_only.any?

        i.update_attributes( h )
    end

    def self.translate_framework_issue( issue )
        h  = {}
        FRAMEWORK_ISSUE_MAP.each do |k, v|
            val = attribute_from_framework_issue( issue, v || k )
            h[k] = val.is_a?( String ) ? val.recode : val
        end

        FRAMEWORK_ISSUE_VARIATION_MAP.each do |k, v|
            val = attribute_from_framework_issue( issue, v || k )
            h[k] = val.is_a?( String ) ? val.recode : val
        end

        h.reject!{ |k, v| PROTECTED.include? k }

        h
    end

    private

    def self.attribute_from_framework_issue( issue, attribute )
        traverse_attributes( issue, attribute )
    end

    def self.traverse_attributes( object, path )
        return if object.nil?

        if path.is_a? Symbol
            return if !object.respond_to?( path )
            return object.send( path )
        end

        child_attribute = path.keys.first
        child_path      = path.values.first

        return if !object.respond_to?( child_attribute )

        traverse_attributes( object.send( child_attribute ), child_path )
    end

    def validate_review_options
        if false_positive && (requires_verification || verified)
            errors.add :false_positive, 'cannot include additional options'
        end
    end

    def validate_verification_steps
        return if ActionController::Base.helpers.strip_tags( verification_steps ) == verification_steps
        errors.add :verification_steps, 'cannot contain HTML, please use Markdown instead'
    end

    def validate_remediation_steps
        return if ActionController::Base.helpers.strip_tags( remediation_steps ) == remediation_steps
        errors.add :remediation_steps, 'cannot contain HTML, please use Markdown instead'
    end

end

.system/arachni-ui-web/app/controllers/issues_controller.rb
=begin
    Copyright 2013-2022 Ecsypno <http://www.ecsypno.com>

    This file is part of the Arachni WebUI project and is subject to
    redistribution and commercial restrictions. Please see the Arachni WebUI
    web site for more information on licensing and terms of use.
=end

class IssuesController < ApplicationController
    include ApplicationHelper
    include IssuesHelper
    include NotificationsHelper

    load_and_authorize_resource

    # GET /issues
    # GET /issues.json
    def index
        @scan = scan

        html_block =    if render_partial?
                            proc { render partial: 'table' }
                        else
                            proc { redirect_to @scan }
                        end

        respond_to do |format|
            format.html( &html_block )
            format.js { render partial: 'table.js' }
            #format.json { render json: @issues }
        end
    end

    # GET /issues/1
    # GET /issues/1.json
    def show
        @issue = scan.issues.find( params.require( :id ) )

        respond_to do |format|
            format.html # show.html.erb
            format.json { render json: @issue }
        end
    end

    # PUT /issues/1
    # PUT /issues/1.json
    def update
        @issue = scan.issues.find( params.require( :id ) )

        @issue.assign_attributes( strong_params )
        changes = @issue.changes

        respond_to do |format|
            if @issue.save

                changes.each do |k, v|
                    old = v.first
                    new = v.last
                    next if old.to_s == new.to_s

                    notify @issue, action: k.to_s, text: "#{v.first} => #{v.last}"
                end

                format.html { redirect_to [@issue.scan, @issue],
                                          notice: 'Issue was successfully updated.' }
                format.json { head :no_content }
            else
                format.html { render action: "show" }
                format.json { render json: @issue.errors,
                                     status: :unprocessable_entity }
            end
        end
    end

    # DELETE /issues/1
    # DELETE /issues/1.json
    def destroy
        @issue = scan.issues.find( params.require( :id ) )
        @issue.destroy

        respond_to do |format|
            format.html { redirect_to scans_issues_url }
            format.json { head :no_content }
        end
    end

    private

    def strong_params
        params.require( :issue ).
            permit( :false_positive, :requires_verification, :remediation_steps,
                    :verified, :verification_steps, :fixed )
    end

end

.system/arachni-ui-web/app/helpers/issues_helper.rb
=begin
    Copyright 2013-2022 Ecsypno <http://www.ecsypno.com>

    This file is part of the Arachni WebUI project and is subject to
    redistribution and commercial restrictions. Please see the Arachni WebUI
    web site for more information on licensing and terms of use.
=end

module IssuesHelper

    def highlight_proof( text, proof, span_class )
        return h( text ) if !proof || !text.include?( proof )

        escaped_proof    = h( proof )
        escaped_response = h( text )

        escaped_response.gsub( escaped_proof,
                               "<span class=\"#{span_class}\">#{escaped_proof}</span>" )
    end

    def scan
        scan = Scan.find( params[:scan_id] )
        params[:overview] == 'true' ? scan.act_as_overview : scan
    end

    def issue_tab_description( type )
        case type
            when 'all'
                'Listing all logged issues.'

            when 'fixed'
                'These issues has been marked as fixed either manually or by '+
                    'not being found by future scan revisions.'

            when 'verified'
                'These issues have been verified as accurate by a human.'

            when 'pending-verification'
                'These issues have been marked as requiring human verification' +
                    ' either manually or by the scanner, due to being logged while ' +
                    'the server was behaving erratically.'

            when 'false-positives'
                'These issues have been marked as false-positives by a human.'

            when 'awaiting-review'
                'These issues haven\'t been reviewed yet.'
        end
    end

    def issue_filter( type )
        case type
            when 'fixed'
                scan.issues.fixed.light
            when 'verified'
                scan.issues.verified.light
            when 'pending-verification'
                scan.issues.pending_verification.light
            when 'false-positives'
                scan.issues.false_positives.light
            when 'awaiting-review'
                scan.issues - (scan.issues.verified +
                    scan.issues.pending_verification +
                    scan.issues.false_positives + scan.issues.fixed)
            else
                scan.issues.light
        end
    end

    def severities_from_issues( issues )
        h = {}
        issues.each do |issue|
            h[issue.severity] ||= []
            h[issue.severity] << issue
        end

        h.each { |severity, cissues| h[severity] = cissues.size }
        h
    end

    def group_issues_by_type( issues )
        h = {}
        issues.each do |issue|
            h[issue.name] ||= []
            h[issue.name] << issue
        end
        h
    end
end

.system/arachni-ui-web/app/views/issues/_accordion.html.erb
<div class="accordion">
    <% issues.each do |issue| %>
        <div class="accordion-group">

            <div class="accordion-heading">
                <%= link_to scan_issue_path( issue.scan, issue ),
                            class: 'btn btn-mini btn-primary' do %>
                    <i class="icon-eye-open"></i>
                <% end %>

                <%= link_to issue, "##{issue.digest}", data: { toggle: 'collapse' } %>
            </div>

            <div id="<%= issue.digest %>" class="accordion-body collapse issue">
                <div class="accordion-inner well">
                    <table class="table table-striped table-hover fixed">
                        <thead>
                        <tr>
                            <th>URL</th>
                            <th>Element</th>
                            <% if issue.vector_name %>
                            <th>Input</th>
                            <% end %>
                        </tr>
                        </thead>
                        <tr>
                            <td class="wrap">
                                <%= link_to issue.url, issue.url  %>
                            </td>
                            <td>
                                <%= issue.vector_type %>
                            </td>
                            <% if issue.vector_name %>
                            <td class="wrap">
                                <%= issue.vector_name %>
                            </td>
                            <% end %>
                        </tr>
                    </table>

                    <p>
                        <%= m issue.description %>
                    </p>
                </div>
            </div>
        </div>
    <%end%>
</div>

.system/arachni-ui-web/app/views/issues/_issue_row.html.erb
<%
   msg, row_class = nil
   icon = 'eye-open'

   if active_tab == 'all'
       icon, msg, row_class =  if issue.requires_verification_and_verified?
                                   [ 'ok', 'Verified', 'success']
                               elsif issue.false_positive?
                                   [ 'remove', 'False-positive', 'error']
                               elsif issue.pending_verification?
                                   [ 'exclamation-sign', 'Needs verification', 'warning']
                               elsif issue.fixed?
                                   [ 'asterisk', 'Fixed', 'info']
                               else
                                   [ 'question-sign', 'Awaiting review', '']
                               end
   end

%>

<tr class="<%= row_class %>">
    <td class="view-issue">
        <a href="<%= scan_issue_path( issue.scan, issue ) %>" rel="tooltip"
           class="btn btn-mini btn-info"
           title="<%= msg %>">
            <i class="icon-<%= icon %>"></i>
        </a>
    </td>

    <td class="wrap">
        <%= link_to issue.url, issue.url, target: '_blank' %>
    </td>
    <td class="wrap"><%= issue.vector_name %></td>
    <td><%= issue.vector_type.capitalize %></td>
</tr>

.system/arachni-ui-web/app/views/issues/_table.js.erb
$("#issues").html( "<%= escape_javascript( render( partial: 'table.html' ).force_encoding( 'utf-8' ) ) %>" );
$("#issues").data( "refresh-url", "<%= escape_javascript scan_issues_path( @scan, params.merge( format: :js ) ) %>" );
$("#revisions-nav-list").html( "<%= escape_javascript( render( partial: 'scans/revisions_nav_list' ).force_encoding( 'utf-8' ) ) %>" );

.system/arachni-ui-web/app/views/issues/_twin_accordion.html.erb
<%

    issues_by_severity = {}
    issues.each do |issue|
        (issues_by_severity[issue.severity] ||= []) << issue
    end

    issues_by_severity.each do |severity, grouped_issues|
        next if grouped_issues.empty?

        lk = rk = []
        lk, rk = *grouped_issues.sort_by { |i| i.name }.chunk( 2 ) if issues.any?
%>

<h3><%= severity %> severity <small>[<%= grouped_issues.size %>]</small></h3>

<div class="row-fluid">
    <div class="<%= class_name %>">
        <%= render partial: '/issues/accordion', locals: { issues: lk }  %>
    </div>
    <div class="<%= class_name %>">
        <%= render partial: '/issues/accordion', locals: { issues: rk }  %>
    </div>
</div>

<% end %>

.system/arachni-ui-web/app/views/issues/new.html.erb
<h1>New issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

.system/arachni-ui-web/app/views/issues/show.html.erb
<% title @issue.to_s.html_safe %>

<% breadcrumb_add 'Scans', @issue.scan %>
<% breadcrumb_add @issue.scan, @issue.scan %>

<%

   browser_subnav = {}
   if @issue.dom_transitions.any?
       browser_subnav = {
           browser_data: 'Browser data',
           browser_data_transitions: '<small>&mdash; Transitions</small>',
           browser_data_body: '<small>&mdash; Body</small>',
       }
   end

   subnav(
       {
           identification_data: 'Identification data',
           vector_data: 'Vector data',
       }.merge(browser_subnav).merge({
           http_data: 'HTTP data',
           http_data_request: '<small>&mdash; Request</small>',
           http_data_response: '<small>&mdash; Response</small>'
       }),
       top: 'Overview'
   )

   not_available = '<p class="alert alert-info">Not available</p>'.html_safe
%>

<% if @issue.references.any? %>
    <% add_to_affixed_sidebar do %>
        <div id="references">
            <h3>References</h3>

            <ul>
                <% @issue.references.each do |k, v| %>
                <li><%= link_to k, v %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
<% end %>

<div id="issues">
    <div class="page-header">
        <h1><%= @issue %>,</h1>

        <div class="lead">
            at <%= link_to @issue.url, @issue.url %>
            <small>&ndash; found by <%= link_to @issue.scan, scan_path( @issue.scan ) %>.</small>
        </div>

        <p class="pull-left label severity-<%= @issue.severity.downcase %>">
            <%= @issue.severity %> severity
        </p>
    </div>

    <div class="description">
        <%= m @issue.description %>
    </div>

    <hr/>

    <% if @issue.remarks.any? %>
        <div class="alert alert-warning">
            <i class="icon-exclamation-sign"></i>
            Remarks:

            <ul class="unstyled">
                <% @issue.remarks.values.flatten.each do |remark| %>
                    <li><%= remark %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <hr/>
    <%= render 'status_messages' %>

    <ul class="nav nav-tabs" id="issue-tabs"
        data-table-container="table-container">
        <li class="active">
            <a href="#issue-<%= @issue.digest %>-technical-details" data-toggle="tab">
                <i class="icon-file-alt"></i>
                Technical details
            </a>
        </li>

        <li>
            <a href="#issue-<%= @issue.digest %>-discussion" data-toggle="tab">
                <i class="icon-comments"></i>
                Discussion <small>[<%= @issue.comments.count %>]</small>
            </a>
        </li>

        <% if @issue.has_verification_steps? %>
            <li>
                <a href="#issue-<%= @issue.digest %>-verification" data-toggle="tab">
                    <i class="icon-check"></i>
                    Verification
                </a>
            </li>
        <% end %>

        <% if @issue.has_remediation_steps? %>
            <li>
                <a href="#issue-<%= @issue.digest %>-remediation" data-toggle="tab">
                    <i class="icon-asterisk"></i>
                    Remediation
                </a>
            </li>
        <% end %>

        <li>
            <a href="#issue-<%= @issue.digest %>-review" data-toggle="tab">
                <i class="icon-edit"></i>
                Review
            </a>
        </li>

        <li>
            <a href="#issue-<%= @issue.digest %>-timeline" data-toggle="tab">
                <i class="icon-reorder"></i>
                Timeline
            </a>
        </li>
    </ul>

    <div class="tab-content">
        <div id="issue-<%= @issue.digest %>-technical-details" class="tab-pane active in">

            <h3 id="identification_data">Identification data</h3>
            <table class="table fixed">
                <thead>
                    <tr>
                        <th>
                            Injected seed

                            <% if @issue.seed %>
                            <a href="#" rel="tooltip"
                               title="This seed uncovered the vulnerable vector during the audit.">
                                <i class="icon-info-sign"></i>
                            </a>
                            <% end %>
                        </th>
                        <th>
                            Signature

                            <% if @issue.signature %>
                            <a href="#" rel="tooltip"
                               title="This signature was used to detect the vulnerability.">
                                <i class="icon-info-sign"></i>
                            </a>
                            <% end %>
                        </th>
                        <th>
                            Proof
                            <% if @issue.proof %>
                                <a href="#" rel="tooltip"
                                   title="This string was used to verify the existence of the vulnerability.">
                                    <i class="icon-info-sign"></i>
                                </a>
                            <% end %>
                        </th>
                    </tr>
                </thead>
                <tr>
                    <td class="wrap"><%= @issue.seed ? @issue.seed : not_available %></td>
                    <td class="wrap"><%= @issue.signature || not_available %></td>
                    <td class="wrap">
                        <% if @issue.proof %>
                            <pre><%= @issue.proof.recode %></pre>
                        <% else %>
                            <%= not_available %>
                        <% end %>
                    </td>
                </tr>
            </table>

            <hr/>

            <h3 id="vector_data">Vector data</h3>

            <% if @issue.vector_html %>
                <pre><%= @issue.vector_html.recode %></pre>
            <% end %>

            <table class="table">
              <thead>
              <tr>
                <th>Type</th>
                <th>URL</th>

                <% if @issue.vector_inputs.any? %>
                    <th>Inputs</th>
                <% end %>
              </tr>
              </thead>
              <tr>
                <td>
                    <code><%= @issue.vector_type %></code>
                </td>
                <td>
                  <%= link_to @issue.url, @issue.url %>
                </td>

                <% if @issue.vector_inputs.any? %>
                <td>
                  <table id="parameters" class="table key-values">
                    <% @issue.vector_inputs.each do |k, v| %>
                        <tr>
                          <th>
                            <%= k.recode %>
                          </th>
                          <td>
                            <%= v.recode %>
                          </td>
                        </tr>
                    <% end %>
                  </table>
                </td>
                <% end %>
              </tr>
            </table>

          <hr/>

          <% if @issue.dom_transitions.any? %>
              <h3 id="browser_data">Browser data</h3>

              <h4 id="browser_data_transitions">Transitions</h4>
              <%= render 'transitions' %>

              <h4 id="browser_data_body">Body</h4>
              <% if @issue.dom_body %>
                  <% if @issue.dom_body_contains_proof? %>
                      <p class="muted">
                        Proof is highlighted in red and scroll-centered.
                      </p>
                  <% end %>

                  <pre id="browser_body_container"><%= highlight_proof( @issue.dom_body, @issue.proof, 'proof' ).recode.html_safe %></pre>

              <% else %>
                  <p class="alert alert-info">
                    Response is not available
                  </p>
              <% end %>
              <hr/>
            <% end %>

            <h3 id="http_data">HTTP data</h3>

            <h4 id="http_data_request">Request</h4>
            <pre><%= @issue.request %></pre>

            <h4 id="http_data_response">Response</h4>

            <% if @issue.response %>
                <% if @issue.response_contains_proof? %>
                    <p class="muted">
                        Proof is highlighted in red and scroll-centered.
                    </p>
                <% end %>

                <pre id="http_response_container"><%= highlight_proof( @issue.response, @issue.proof, 'proof' ).recode.html_safe %></pre>

            <% else %>
                <p class="alert alert-info">
                    Response is not available
                </p>
            <% end %>
        </div>

        <div id="issue-<%= @issue.digest %>-discussion" class="tab-pane">
            <%= render partial: 'comments/list',
                       locals: { comments: @issue.comments,
                                 list_url: scan_issue_comments_path( @issue.scan, @issue, partial: true )
                       } %>

            <%= render partial: 'comments/form', locals: { commentable: @issue } %>
        </div>

        <% if @issue.has_verification_steps? %>
            <div id="issue-<%= @issue.digest %>-verification" class="tab-pane">
                <h3>
                    Verification steps
                </h3>

                <p>
                    <%= m @issue.verification_steps %>
                </p>

            </div>
        <% end %>

        <% if @issue.has_remediation_steps? %>
            <div id="issue-<%= @issue.digest %>-remediation" class="tab-pane">
                <h3>
                    Remediation steps
                </h3>

                <p>
                    <%= m @issue.remediation_steps %>
                </p>

            </div>
        <% end %>

        <div id="issue-<%= @issue.digest %>-review" class="tab-pane">
            <%= render 'form' %>
        </div>

        <div id="issue-<%= @issue.digest %>-timeline" class="tab-pane">
            <ul class="unstyled">

            <% @issue.timeline.each do |t| %>
                <li>
                    <%= t.action_description.capitalize %>

                    <% if t.actor %>
                        by <%= link_to t.actor, user_path( t.actor ) %>
                    <% end %>

                    <small class="muted">&ndash; <%= l t.created_at %></small>

                    <% if t.text %>
                        <blockquote class="muted">
                            <%= t.text %>
                        </blockquote>
                    <% end %>
                </li>
            <% end %>

                <li>Created <small class="muted">&ndash; <%= l @issue.created_at %></small></li>
            </ul>
        </div>

    </div>
</div>